# Generated by Django 4.2.16 on 2024-09-24 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('job_url', models.URLField(blank=True, max_length=500)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.FileField(upload_to='cover_letters/')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Offer', 'Offer')], default='Applied', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank='Untitled Company', max_length=255)),
                ('job_title', models.CharField(blank='Untitled Job', max_length=255)),
                ('posting_url', models.URLField(blank='None', max_length=500)),
                ('location', models.CharField(blank='Unspecified', max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('description', models.TextField(blank='No description provided')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
