# Generated by Django 4.2.16 on 2024-09-22 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_title',
            field=models.CharField(default='Untitled Job', max_length=255),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='posting_url',
            field=models.URLField(default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(default='Untitled Company', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(default='Unspecified', max_length=255),
        ),
    ]
