# Generated by Django 4.2.16 on 2024-09-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_jobposting_date_created_jobposting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(blank='Untitled Company', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(blank='No description provided'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_title',
            field=models.CharField(blank='Untitled Job', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='posting_url',
            field=models.URLField(blank='None', max_length=500),
        ),
    ]
