# Generated by Django 4.2.16 on 2024-09-24 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_jobposting_is_remote_alter_jobposting_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
