# Generated by Django 4.2.16 on 2024-10-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_document_document_name'),
        ('tracker', '0002_remove_jobapplication_company_name_and_more'),
        ('tracker', '0005_document'),
    ]

    operations = [
    ]
